modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="kaletaold"
version="1.1.0"
displayName="森罗物语：老牌酒馆"
logoFile="kaletaold.png"
credits=""
authors="LrcxzzMC"
description='''
森罗物语酒馆的附属模组
'''

[[dependencies.kaletaold]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.kaletaold]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.kaletaold]]
modId="kaleidoscope_tavern"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"